### ISSUE TITLE
Primordials is not defined

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [englercj/lttp-phaser#10]
I followed the readme and this fails at `npm run` and `npm run-script build`

```
$ npm run

> lttp@1.0.0 start X:\Big_Code\lttp
> npm run dev


> lttp@1.0.0 dev X:\Big_Code\lttp
> gulp clean && gulp dev

fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (X:\Big_Code\lttp\node_modules\natives\index.js:143:24)
    at Object.req [as require] (X:\Big_Code\lttp\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (X:\Big_Code\lttp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lttp@1.0.0 dev: `gulp clean && gulp dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lttp@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Proto\AppData\Roaming\npm-cache\_logs\2020-10-16T02_17_50_669Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lttp@1.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lttp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Proto\AppData\Roaming\npm-cache\_logs\2020-10-16T02_17_50_681Z-debug.log
```

Seems fs cannot require `primordials` but it is not a package as far as I can tell.

**Comment by MylchenkoAlexandr** [comment]
anybody solve the problem?

**Comment by englercj** [comment]
I haven't looked at this code in like 5 years. I doubt it works.
