### ISSUE TITLE
gulp clean && gulp dev fails on my system (OS X version 10.9.5 running npm version 2.11.3)

### ISSUE THREAD

**Issue by str8ballin215** [englercj/lttp-phaser#4]
I'm running npm version 2.11.3 on OS X version 10.9.5.

Running npm install && npm start works for _awhile_, but fails eventually on the following line:

`> gulp clean && gulp dev`

Then all these errors occur:

```
/Users/.../Documents/git/lttp/gulpfile.js:7
const gulp      = require('gulp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/.../Documents/git/lttp/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/.../Documents/git/lttp/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/.../Documents/git/lttp/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lttp@1.0.0 dev: `gulp clean && gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lttp@1.0.0 dev script 'gulp clean && gulp dev'.
npm ERR! This is most likely a problem with the lttp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean && gulp dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls lttp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../Documents/git/lttp/npm-debug.log
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lttp@1.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lttp@1.0.0 start script 'npm run dev'.
npm ERR! This is most likely a problem with the lttp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls lttp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../Documents/git/lttp/npm-debug.log`

FYI - this is the content of the npm-debug.log file:

`0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lttp@1.0.0
6 info start lttp@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info lttp@1.0.0 Failed to exec start script
9 verbose stack Error: lttp@1.0.0 start: `npm run dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid lttp@1.0.0
11 verbose cwd /Users/.../Documents/git/lttp
12 error Darwin 13.4.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error lttp@1.0.0 start: `npm run dev`
17 error Exit status 1
18 error Failed at the lttp@1.0.0 start script 'npm run dev'.
18 error This is most likely a problem with the lttp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run dev
18 error You can get their info via:
18 error     npm owner ls lttp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by englercj** [comment]
What version of node are you using? Its working well for me:

```
$ npm -v
2.14.12

$ node -v
v4.2.5

$ npm ls --depth 0
lttp@1.0.0 C:\Users\Chad\repos\lttp
├── css-loader@0.23.1
├── del@2.2.0
├── extract-text-webpack-plugin@1.0.1
├── file-loader@0.8.5
├── gulp@3.9.1
├── gulp-phaser-tiled-pack@1.1.0
├── gulp-tslint@4.3.3
├── gulp-util@3.0.7
├── html-webpack-plugin@2.9.0
├── image-webpack-loader@1.6.3
├── less@2.6.1
├── less-loader@2.2.2
├── lz-string@1.4.4
├── phaser@2.4.6
├── phaser-debug@2.0.0 -> C:\Users\Chad\repos\phaser-debug
├── phaser-tiled@2.0.0
├── run-sequence@1.1.5
├── script-loader@0.6.1
├── ts-loader@0.8.1
├── tslint@3.5.0
├── typescript@1.8.7
├── webpack@1.12.14
└── webpack-dev-server@1.14.1
```

**Comment by str8ballin215** [comment]
Upgraded to the recommended version and it works - thanks!
